client/api_object.go
Add CreateFolder API
```go
cli, err := client.New(ChainID, Endpoint, client.Option{
DefaultAccount: account,
GrpcDialOption: grpc.WithTransportCredentials(insecure.NewCredentials())},
)
assert.NoError(t, err)
ctx := context.Background()
var opts types.CreateObjectOptions
txHash, err := cli.CreateFolder(ctx, "bucket name", "/dir/subdir/", opts )
assert.NoError(t, err)
t.Logf("Acc: %s", txHash)
waitForTx, err := cli.WaitForTx(ctx, txHash)
assert.NoError(t, err)
t.Logf("Wair for tx: %s", waitForTx.String())
```
* add create folder api
* ...
=> feat: add createfolder api

client/api_client.go
fix the URL error, the virtual host URL may have more than one object name.
URL may contain more than one object name, need  remove duplicate logic
NA
* fix the URL error, remove duplicate logic
=> fix: fix  potential url error of http request

client/api_account.go, client/api_client.go, client/api_payment.go, client/api_sp.go, e2e/e2e_basic_test.go
Add payment client and sp functions.
Add payment client in new SDK, make it easier to invoke payment related queries and transactions.
Add more functions in Storage API.
```golang
// create payment account
paymentAccountsBeforeCreate, err := cli.GetPaymentAccountsByOwner(ctx, account.GetAddress().String())
s.Require().NoError(err)
txHash, err := cli.CreatePaymentAccount(ctx, account.GetAddress().String(), types2.TxOption{})
s.Require().NoError(err)
t.Logf("Acc: %s", txHash)
waitForTx, err := cli.WaitForTx(ctx, txHash)
s.Require().NoError(err)
t.Logf("Wair for tx: %s", waitForTx.String())
paymentAccountsByOwnerAfterCreate, err := cli.GetPaymentAccountsByOwner(ctx, account.GetAddress().String())
s.Require().NoError(err)
s.Require().Equal(len(paymentAccountsByOwnerAfterCreate)-len(paymentAcco …
```
=> feat: add payment client and sp functions

types/list.go
- Update Metadata's ObjectMeta and BucketMeta struct to be latest version SP api returns
- Restore ObjectMeta that was mistakenly changed in refactoring
For ListObjects and ListBuckets to return data reflects latest schema
N/A
* Update metadata Object & Bucket schema
* Restore ObjectMeta struct
=> feat: update metadata schema and restore ObjectMeta

client/api_bucket.go, client/api_challenge.go, client/api_client.go, client/api_object.go, client/api_sp.go, types/const.go, types/option.go
1. set the default txn broadcast mode as block of create object, create bucket, update bucket
2. add trace option to dump http info of SP message
3. add error log 
help to locate the error 
dump message
cli.EnableTrace(nil, true)
* add trace option to dump http info
=> refactor: add err log and trace for SP msg

client/api_challenge.go
This pr removes challenge address verify when it is empty.
Challenge address could be empty.
NA
* challenge
=> fix: remove challenge address verify when it is empty

client/api_bucket.go, client/api_object.go, types/option.go
support updating the visibility of the object,  added the interface of UpdateObjectVisibility in api_object.go
update object visibility is needed to supported
`client.UpdateObjectVisibility(ctx, bucketName, objectName, storageTypes.VISIBILITY_TYPE_PRIVATE, opt)
`
* support updating the visibility of the object
=> feat: support update-object

client/api_challenge.go, examples/group.go, examples/permission.go, examples/storage.go, types/const.go, types/option.go
When challenging secondary sp, go sdk obtains the sp endpoint through the bucket name by default, not the secondary sp endpoint.
1) add options to pass the SP address or endpoint directly
2) if options is not provided , get the SP address by redanduncy index
support getting challenge info from the secondary sp
```
cli.GetChallengeInfo(ctx, objectID,  0,  -1,  types.GetChallengeInfoOptions{SPAddress: "0x.."})
cli.GetChallengeInfo(ctx, objectID,  0,  -1,  types.GetChallengeInfoOptions{Endpoint: "https://gnfd-testnet-sp-1.nodereal.io"})
```
*  fix: support getting challenge info from the secondary sp
=> fix: support challenge to secondary sp 

client/api_bucket.go, client/api_object.go, types/const.go
config timeout for context which passed in waitForTxn of createObject and createBucket 
when txn failed and can not fetch info on chain. , this function will fall into infinite waiting and cannot exit 
NA
* config timeout to context
=> fix:  config timeout to context in createObject and createBucket 

README.md
Parameter order has been changed on example code.
Example was not working. client.New function's parameters has been changed on API side but forgotten on example.
NA
*move chainId to first order
=> fix: parameter orders on example snippet on Readme

.github/workflows/e2e.yml, client/api_challenge.go, client/api_client.go, client/api_object.go, e2e/e2e_storage_test.go, examples/storage.go, pkg/utils/utils.go, types/const.go, types/option.go, types/types.go
if primary SP not in service , the  client can get piece data from secondary SP and decode the origin segment.
Client.RecoverObjectBySecondary support same option as getObject to support range recovery
support recovery in client
```
filePath := "downloadfile"
err = s.Client.RecoverObjectBySecondary(s.ClientContext, bucketName, objectName, filePath, types.GetObjectOption{})
```
* support recovery object in client
=> feat:  support recovery in client

.github/workflows/e2e.yml, client/api_bucket.go, client/api_object.go, e2e/e2e_storage_test.go, examples/storage.go, types/list.go
support list objects by id and list buckets by id
N/A
```
curl --location --request POST 'localhost:9133/?objects-query' \
--header 'Authorization: authTypeV2 ECDSA-secp256k1, Signature=1234567812345678123456781234567812345678123456781234567812345678' \
--header 'Content-Type: application/json' \
--data-raw '{
"ids": [333,666]
}'
```
```
curl --location --request POST 'localhost:9133/?buckets-query' \
--header 'Authorization: authTypeV2 ECDSA-secp256k1, Signature=1234567812345678123456781234567812345678123456781234567812345678' \
--header 'Content-Type: application/json' \
--data-raw '{
"ids": [222]
}'
```
Notable changes: 
* support list objects by id and list buckets by id
=> feat: list objects & buckets

client/api_client.go, client/api_off_chain_auth.go, examples/common.go, examples/offchainauth.go, go.mod, go.sum
SP supports both v1 and off-chain-auth as the authentication types.  In go-sdk, this pr will support the off-chain-auth.
Usually, go-sdk users don't have to use off-chain-auth, as they can use private key to sign the v1 authType agains the request. 
However, we are reported that some users might want to use go-sdk to test or detect if a giving SP meet our SP specification, which requires SP to implement off-chain-auth mechanism.  To test mechanism, the tester needs to :
1. create EdDSA private key and public key pairs
2. register the EdDSA public key to all SPs
3. sign request by using EdDSA private key.
These procedures are complex to use unless we simplify them in go-sdk
Check the examples in the pr:
greenfield-go-sdk/examples/offchainauth.go
* add offchainauth …
=> feat: support off-chain-auth to sign the request

client/api_object.go
fix continuation token is decoded when sending the request
N/A
N/A
* fix continuation token is decoded when sending the request
=> fix: list object decoded continuation token

.github/workflows/e2e.yml, client/api_basic.go, client/api_client.go, client/api_object.go, client/api_off_chain_auth.go, e2e/e2e_migrate_bucket_test.go, e2e/e2e_storage_test.go, examples/common.go, examples/offchainauth.go, examples/storage.go, examples/storage_by_offchainauth.go, go.mod, go.sum, types/const.go, types/types.go
Refactoring auth code after security review
Notable changes: 
1. Make the offchainauth's signedMsg be consistent with the V1's signedMsg, which are constructed by commonhttp.GetMsgToSign
5. Add "X-Gnfd-Expiry-Timestamp" header for both off-chain-auth and V1 auth, in order to make the replay attack impossible after sig is expired.
=> feat: auth refactoring

client/api_off_chain_auth.go, go.mod, go.sum
feat: rename personal sign
It was "PersonalSign ECDSA-secp256k1" and it is now renamed to "GNFD1-ETH-PERSONAL_SIGN"
=> feat: rename personal sign auth name

client/api_group.go, examples/group.go, examples/payment.go, types/list.go
support list groups by ids
update payment account info in list user payment account
N/A
N/A
* support list groups by ids
* update payment account info in list user payment account
* update examples cases
=> feat: list groups by ids

client/api_bucket.go, client/api_challenge.go, client/api_client.go, client/api_object.go, go.mod, go.sum, types/const.go, types/list.go, types/option.go
support option to switch v2 version of challenge API of GetChallengeInfo to fix challenge API issue . The GetChallengeInfo will stay  compatible with the old version.
The V2 challenge API  will return the XML body with the intergrityHash , pieceHashes and piece data info
the new challenge API  will change protocol
// if  need use V2 version , set the option of UseV2version as true
// default using V1 version API to keep  compatible
`GetChallengeInfo( types.GetChallengeInfoOptions{UseV2version : true} )`
* support v2 version of challenge API
=> feat: support challenge admin v2 API

client/api_object.go, e2e/e2e_storage_test.go
fix ListObjectPoliciesResponse unmarshal failed bug
N/A
* fix ListObjectPoliciesResponse unmarshal failed bug
=> fix: ListObjectPoliciesResponse unmarshal failed

.github/workflows/e2e.yml, types/types.go
feat: add proto message info to ObjectDetail type so that it can be marshalled into json by using jsonpb
In clients (e.g. greenfield-cmd), they might want to use jsonpb to marshal the "ObjectDetail" type returned by go-sdk. Because the fields in "ObjectDetail" type are all proto messages. 
N/A
* protobuf annotations
* add necessary methods of proto message type
=> feat: add proto message info to ObjectDetail type so that it can be marshalled into json by using jsonpb

.github/workflows/e2e.yml, client/api_bucket.go, client/api_group.go, client/api_object.go, e2e/e2e_storage_test.go, go.mod, go.sum
fix: remove tags field when creating object/group/bucket
Adapting changes from greenfield chain https://github.com/bnb-chain/greenfield/pull/543
N/A
* remove tags field when creating object/group/bucket
* Use multi msg when creating object/group/bucket if tags are needed.
=> fix: remove tags field when creating object/group/bucket

client/api_client.go, client/api_object.go, e2e/e2e_storage_test.go, types/option.go
Add ForceToUseSpecifiedSpEndpointForDownloadOnly in api client opt to determine if need to refresh SPs. If ForceToUseSpecifiedSpEndpointForDownloadOnly option is set, the client can only make download requests, and can only download from the fixed endpoint. 
Make go-sdk process speed faster.
N/A 
* api client option
* api client
=> feat: update get object for speed

client/api_object.go, e2e/e2e_storage_test.go
=> perf: hide GetObjectResumableUploadOffset interface

client/api_client.go, client/api_off_chain_auth.go, go.mod, go.sum
off-chain-auth simplification
We aim to provide a simplified off-chain-auth implementation.   It will remove the "key nonce" concept in the original off-chain-auth.
In addition, for EdDSA algorithm, we will use the Ed25519 as the EdDSA curve.
see https://github.com/bnb-chain/BEPs/pull/361
The following example demostrate how to use the new simplified off-chain-auth by using greenfield-go-sdk. 
If you are developing a web-based dAPP, you should use greenfield-js-sdk to integrate the new simplified off-chain-auth
```
package main
import (
"bytes"
"context"
"errors"
"fmt"
"io"
"log"
"time"
"github.com/bnb-chain/greenfield-go-sdk/client"
"github.com/bnb-chain/greenfield-go-sdk/types"
storageTypes "github.com/bnb-chain/greenfield/x/storage/types"
)
const rpcAddr = "http://localhost:26750" …
```
=> feat: off-chain-auth simplification in go-sdk

client/api_bucket.go, go.mod, go.sum, types/option.go
This pr will add new messages and queries introduced:
+ MsgSetBucketFlowRateLimit
+ QueryPaymentAccountBucketFlowRateLimit
Add new messages and queries
n/a
* add new messages and queries
=> feat: add SetBucketFlowRateLimit

client/api_object.go, e2e/e2e_storage_test.go
=> feat: delegate create folder

.github/workflows/e2e.yml, client/api_bucket.go, client/api_object.go, e2e/e2e_storage_test.go, types/list.go
api to get virtual group family id from SP
* ...
=> feat: api to get virtual group family id from SP

.github/workflows/e2e.yml, .github/workflows/lint-pr.yml, go.mod, go.sum
This release is the official release of greenfield-go-sdk for the Greenfield v1.7.0.
N/A
N/A
N/A
=> docs: prepare go-sdk release v1.7.0
