bnb-chain/greenfield-go-sdk

client/api_client.go, go.mod, go.sum
adapt change in gnfd sdk, use rpc ep to init chain client
NA
NA
NA
=> feat: adapt change in gnfd sdk

.github/workflows/e2e.yml, README.md, client/api_account.go, client/api_basic.go, client/api_bucket.go, client/api_challenge.go, client/api_client.go, client/api_group.go, client/api_object.go, client/api_proposal.go, client/api_sp.go, doc.go, e2e/basesuite/suite.go, e2e/e2e_basic_test.go, e2e/e2e_sp_test.go, e2e/e2e_storage_test.go, example/basic.go, go.mod, go.sum, types/account.go, types/errors.go, types/list.go, types/option.go
A new go sdk client implement
- Easy to use
- Interface friendly
```
package main
import (
"context"
"log"
"github.com/bnb-chain/greenfield-go-sdk/client"
"github.com/bnb-chain/greenfield-go-sdk/types"
"google.golang.org/grpc"
"google.golang.org/grpc/credentials/insecure"
)
func main() {
privateKey := "<Your own private key>"
account, err := types.NewAccountFromPrivateKey("test", privateKey)
if err != nil {
log.Fatalf("New account from private key error, %v", err)
}
cli, err := client.New("greenfield_9000-121", "http://localhost:26750", client.Option{DefaultAccount: account})
if err != nil {
log.Fatalf("unable to new greenfield client, %v", err)
}
ctx := context.Background()
nodeInfo, versionInfo, err := cli.GetNodeInfo(ctx)
if err != nil {
log.Fatalf("unable to get node info, %v", err)
} …
```
=> feat: new go sdk client

Makefile, client/api_account.go, client/api_bucket.go, client/api_challenge.go, client/api_client.go, client/api_crosschain.go, client/api_distribution.go, client/api_validator.go, e2e/e2e_basic_test.go, e2e/e2e_validator_test.go, types/account.go, types/errors.go
add more msgs
enable the usage of msgs
NA
* NA
=> feat: new go-sdk add msgs

client/api_challenge.go
This pr will add parameter query for challenge module.
For querying parameters.
NA
* challenge api
=> feat: add parameter query for challenge module

client/api_account.go, client/api_basic.go, client/api_bucket.go, client/api_challenge.go, client/api_client.go, client/api_crosschain.go, client/api_distribution.go, client/api_feegrant.go, client/api_group.go, client/api_object.go, client/api_payment.go, client/api_proposal.go, client/api_validator.go, e2e/e2e_basic_test.go, e2e/e2e_feegrant_test.go, e2e/e2e_sp_test.go, e2e/e2e_storage_test.go, e2e/e2e_validator_test.go, pkg/utils/policy.go, types/account.go, types/types.go
add fee grant apis
add fee grant apis
na
* add apis for fee grant
=> feat: add fee grant apis

go.mod, go.sum
This pr will update the dependency for `github.com/bnb-chain/greenfield-common`.
update dependency for greenfield-common
N/A
* update dependency for greenfield-common
=> feat: update dependency for greenfield-common

README.md, client/api_bucket.go, client/api_object.go, types/option.go
1. update readme 
2. support createObject, createBucket as a sync mode
support sync mode
NA
*  support sync mode
=> feat: support create object,bucket default sync mode

.github/workflows/e2e.yml, client/api_bucket.go
Fix get create bucket approval error msg
N/A
N/A
N/A
=> fix: fix get create bucket approval error msg

client/api_challenge.go, go.mod, go.sum
This pr will sync to the latest greenfield and update challenge query api.
Update api
NA
* challenge api
=> feat: update challenge query api

examples/permission.go, examples/storage.go
fix example err
fix  err
NA.
* fix example err
=> fix: fix example err

.github/workflows/e2e.yml, client/api_object.go
upgrade the dependency
need to update dependency
NA
*  need to update
=> fix: upgrade dependency of greenfield

client/api_object.go
The query error log is confusing  when call the putObject function, remove head sp object logic before put object
remove  unuseful error log
NA
* remove head sp object logic
=> fix: remove head sp object logic before put object

client/api_bucket.go, client/api_client.go, client/api_group.go, client/api_object.go, examples/common.go, examples/group.go, examples/storage.go, types/option.go
Aliyun sp may cause Failure to synchronize data in time
N/A
N/A
* fix go-sdk internal sp selection issue for metadata
=> fix: sp metadata

client/api_bucket.go, client/api_client.go, e2e/e2e_basic_test.go, e2e/e2e_storage_test.go, go.mod, go.sum, types/const.go, types/option.go
add migrate bucket interface
support user to migrate bucket
NA
* NA
=> feat: add migrate bucket interface

client/api_challenge.go, client/api_object.go, e2e/e2e_storage_test.go, go.mod, go.sum, types/types.go
Return detail info of headObject, include object info and gvg
need gvg info to getSecondarySP
NA
* NA
=> feat: adapt new head object

client/api_client.go, client/api_off_chain_auth.go, examples/offchainauth.go, go.mod, go.sum
feat: support off-chain-auth in sp exit
*  support off-chain-auth in sp exit
*  fix the issue that c.spAddressEndpoints were not initialized when client is created.
=> feat: support off-chain-auth in sp exit

examples/crosschain.go, examples/offchainauth.go, examples/payment.go
=> fix: fix example

.github/workflows/e2e.yml, client/api_basic.go, client/api_client.go, e2e/basesuite/suite.go, e2e/e2e_storage_test.go, go.mod, go.sum, types/const.go
Enable websocket connection as option for Client. 
For the need of building long connection with Node
```
s.Client, err = client.New(ChainID, Endpoint, client.Option{
UseWebSocketConn: true,
})
```
* NA
=> feat: Enable websocket conn option

client/api_client.go, client/api_object.go, e2e/e2e_storage_test.go, go.mod, go.sum, types/const.go, types/option.go
support parallel computing hash when creating object
improve performance of create object
NA
* support parallel computing hash
=> feat: support parallel compute hash

.github/workflows/e2e.yml, e2e/e2e_storage_test.go
update dependency and e2e
for release new version
NA
* ...
=> fix: update-denpendency

client/api_bucket.go, client/api_object.go, examples/storage.go, types/option.go
add removed option for list objects and list buckets
N/A
N/A
* add removed option for list objects and list buckets
=> feat: list removed

client/api_client.go, go.mod
fix nil pointer err of getEndpointByOpt
N/A
N/A
* fix nil pointer err of getEndpointByOpt
=> fix: nil err for getEndpointByOpt

.github/workflows/e2e.yml, client/api_bucket.go, client/api_group.go, client/api_object.go, examples/group.go, types/list.go, types/option.go
1. add group apis: GetGroupMembers/GetUserGroups/GetUserOwnedGroups
2. update ListObjectsByObjectID & ListBucketsByBucketID 
N/A
N/A
* support GetGroupMembers/GetUserGroups/GetUserOwnedGroups
* update ListObjectsByObjectID & ListBucketsByBucketID from post to get
=> feat: add group apis

client/api_bucket.go, client/api_group.go, examples/group.go, types/option.go
fix group comments
N/A
N/A
* fix group comments
=> fix: group comments

.github/workflows/e2e.yml, e2e/basesuite/suite.go
=> fix: sp tag

.github/workflows/e2e.yml, client/api_bucket.go, client/api_group.go, client/api_object.go, examples/group.go, types/list.go
Adapt to Meta Service api response body change from json to xml, shall not have difference on client side. 
N/A
N/A
* meta service bucket apis
* meta service object apis
* meta service group apis
=> feat: json response body to xml for meta service

.github/workflows/e2e.yml, client/api_bucket.go, client/api_group.go, client/api_object.go, examples/group.go, types/list.go
this release adapts change from `Greenfield Storage Provider`
NA
NA
* https://github.com/bnb-chain/greenfield-go-sdk/pull/161
=> release: prepare for release v0.2.4-alpha.3

.github/workflows/e2e.yml, e2e/e2e_storage_test.go, types/list.go
=> feat: support get consumed free quota

client/api_account.go, client/api_basic.go, client/api_bucket.go, client/api_challenge.go, client/api_client.go, client/api_crosschain.go, client/api_distribution.go, client/api_feegrant.go, client/api_object.go, client/api_payment.go, client/api_proposal.go, client/api_sp.go, client/api_validator.go
the pr fix a tx response issue, In the case  tx is not success, and err is nil, failure detail will be exposed via tx status code,
* ...
=> fix: should check for tx response status code as tx failure might not return err

.github/workflows/e2e.yml, client/api_object.go, e2e/e2e_storage_test.go
add a e2e test for uploading tampering object
* ...
=> test: add e2e for tampering object

client/api_validator.go, e2e/basesuite/suite.go, e2e/e2e_validator_test.go
fix impeach validator api, which need to go through a proposal. 
* ...
=> fix:  fix impeach validator api

client/api_crosschain.go, client/api_distribution.go, client/api_proposal.go
Refine documents of the cross-chain and cosmos related apis.
Improve docs
NA
* NA
=> docs: refine the go doc of the cross-chain related apis

client/api_payment.go
Refine documents of payment apis.
Improve docs
NA
* NA
=> docs: refine the go doc of payment apis

client/api_validator.go
Refine documents of validator/staking apis.
Improve docs
NA
* NA
=> docs: refine the go doc of validator/staking apis

client/api_client.go, client/api_off_chain_auth.go
fix: go-sdk doc for off chain auth
=> fix: go-sdk doc for off chain auth

client/api_challenge.go, types/option.go, types/types.go
Refine documents of challenge apis.
Improve docs
NA
* NA
=> docs: refine the go doc of challenge apis

e2e/e2e_migrate_bucket_test.go
the  MigrateBucket has changed , so need to update the e2e case
* ...
=> fix: fix e2e

types/list.go
fix list comments of list.go
* ...
=> fix: fix list comments

types/list.go
=> fix: fix list.go comment

client/api_group.go
=> fix: fix group api

types/option.go
=> fix: remove unuse option

client/api_object.go, types/option.go
=> feat: cancel object update

types/list.go
=> fix: get bucket quota

types/list.go
update bucket OffChainStatus
N/A
N/A
* update bucket OffChainStatus
=> fix: update bucket OffChainStatus

client/api_off_chain_auth.go, go.mod, go.sum, pkg/utils/utils.go
fix security issues
N/A
N/A
* fix security issues
=> fix: update security issue

client/api_bucket.go, client/api_virtual_group.go, go.mod, go.sum
[add a description of your changes here...](fix: replace picking strategy)
N/A
N/A
* fix: replace picking strategy
=> fix: replace picking strategy

examples/delegate_upload_object.go
add delegate upload example
* ...
=> docs: add delegate upload example

.github/workflows/e2e.yml, .github/workflows/lint.yml, examples/delegate_upload_object.go
Fix delegate upload object example
N/A
N/A
* delegate upload object example
=> release: v1.7.4 fix delegate upload example
